# Generated by Django 4.2 on 2023-08-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
