# Generated by Django 4.2 on 2023-08-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=10),
        ),
    ]
