# Generated by Django 4.2 on 2023-08-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_rename_interraction_count_post_interaction_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='interaction_text',
            new_name='interaction_count',
        ),
    ]
